[package]
name = "rust-utils"
version = "1.5.0"
edition = "2021"

[features]
default = ["string_stream", "pipe", "collect_vec"]
collect_vec = []
string_stream = []
pipe = []
vec2d = []
byte_readers = []

[dependencies]
