[package]
name = "rust-utils"
version = "1.4.1"
edition = "2021"

[features]
default = ["string_stream", "pipe", "collect_vec"]
collect_vec = []
string_stream = []
pipe = []
vec2d = []

[dependencies]
