name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Get version
      uses: SebRollen/toml-action@v1.2.0
      id: read_toml
      with:
        file: 'Cargo.toml'
        field: 'package.version'
    - name: Create tag
      run: git tag -f v{{steps.read_toml.outputs.value}}
